syntax = 'All'
column_width = 76
line_endings = 'Unix'
indent_type = 'Tabs'
indent_width = 4
quote_style = 'ForceSingle'
call_parentheses = 'Always'
space_after_function_names = 'Definitions'
collapse_simple_statement = 'Never'

[sort_requires]
enabled = true
